account_id = '801755e645b3d1da0d3c826fd5095967'
name = "vite-test"
route = ''
site = {bucket = "dist", entry-point = "workers-site"}
target_type = "webpack"
type = 'webpack'
usage_model = ''
workers_dev = true
zone_id = ''

[env.staging]
name = "my-worker-staging"
vars = {ENVIRONMENT = "staging"}

[env.name1]
name = 'new-name-envi'
vars = {ENVIRONMENT = 'naming'}
